// Package plugin owns per-project Dockerfile-fragment plugins: their on-disk
// identity, validation, layered-Dockerfile generation, and the derived image
// tag a plugin'd project runs from. The functions in this file are pure; the
// filesystem operations live in store.go.
package plugin

import (
	// SHA-1 is an identifier hash here (like internal/projectid), not a
	// security primitive: plugin ids are short names for fragment files.
	//nolint:gosec // G505: SHA-1 used as identifier hash, not crypto.
	"crypto/sha1"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"
)

// descriptionDirective is the comment prefix that carries a plugin's one-line
// description. It must appear in every stored fragment.
const descriptionDirective = "# gbx:description:"

// idLen is how many leading hex chars of the SHA-1 form a plugin id. Pids are
// 12; a single project has only a handful of plugins, so 8 is ample.
const idLen = 8

// Plugin is one stored Dockerfile fragment.
type Plugin struct {
	ModTime     time.Time
	ID          string
	Description string
	Path        string
	Content     string
}

// HashID returns the plugin id for content created at ts: the first idLen
// lowercase hex chars of sha1(content + RFC3339Nano timestamp). The timestamp
// makes two plugins with identical content still get distinct ids.
func HashID(content string, ts time.Time) string {
	//nolint:gosec // G401: identifier hash, not cryptographic; see import comment.
	sum := sha1.Sum([]byte(content + ts.UTC().Format(time.RFC3339Nano)))
	return hex.EncodeToString(sum[:])[:idLen]
}

// ParseDescription extracts the text following the description directive.
// Returns an error if the directive is absent or its text is empty.
func ParseDescription(content string) (string, error) {
	for line := range strings.SplitSeq(content, "\n") {
		t := strings.TrimSpace(line)
		if !strings.HasPrefix(t, "#") {
			continue
		}
		// Normalize "#   gbx:description:" → "gbx:description:".
		body := strings.TrimSpace(strings.TrimPrefix(t, "#"))
		const key = "gbx:description:"
		if rest, ok := strings.CutPrefix(body, key); ok {
			desc := strings.TrimSpace(rest)
			if desc == "" {
				return "", errors.New("plugin description is empty (fill in the `# gbx:description:` line)")
			}
			return desc, nil
		}
	}
	return "", errors.New("plugin is missing a `# gbx:description:` line")
}

// Validate reports whether content is storable as a fragment: it must carry a
// non-empty description directive and must not contain a FROM or ADD
// instruction (FROM is generated; ADD is disallowed). Comment lines are
// ignored, so a commented FROM/ADD in the instructional template is fine.
func Validate(content string) error {
	if _, err := ParseDescription(content); err != nil {
		return err
	}
	for i, line := range strings.Split(content, "\n") {
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, "#") {
			continue
		}
		kw := strings.ToUpper(strings.Fields(t)[0])
		switch kw {
		case "FROM":
			return fmt.Errorf("line %d: plugins must not contain a FROM line (it is generated for you)", i+1)
		case "ADD":
			return fmt.Errorf("line %d: ADD is not allowed in plugins; use COPY or RUN curl", i+1)
		}
	}
	return nil
}

// DerivedImageTag returns the per-project image tag derived from base and pid,
// e.g. ("glovebox-agent:local", "abc123") -> "glovebox-agent-abc123:local".
func DerivedImageTag(base, pid string) string {
	if i := strings.LastIndex(base, ":"); i >= 0 {
		return base[:i] + "-" + pid + base[i:]
	}
	return base + "-" + pid
}

// GenerateDockerfile renders the layered Dockerfile for plugins on top of base.
// Callers pass plugins already in the desired (id-sorted) order.
func GenerateDockerfile(base string, plugins []Plugin) string {
	var b strings.Builder
	b.WriteString("# Generated by `gbx rebuild` from this project's plugins. Do not edit.\n")
	b.WriteString("FROM " + base + "\n")
	for _, p := range plugins {
		b.WriteString("\n# plugin " + p.ID + ": " + p.Description + "\n")
		b.WriteString(p.Content)
		if !strings.HasSuffix(p.Content, "\n") {
			b.WriteString("\n")
		}
	}
	return b.String()
}

// Template returns the seed content shown in the editor by `gbx plugin add`.
// Its description directive is intentionally empty so the fragment fails
// validation until the user fills it in.
func Template(pid string) string {
	return `# glovebox plugin — Dockerfile fragment for project ` + pid + `
#
# These lines are layered ON TOP OF the base agent image:
#
#     FROM glovebox-agent:local
#     <everything you write below>
#
# Rules:
#   - Do NOT add your own FROM line (it is generated for you).
#   - The build runs as root; the container later runs as the gbx user.
#   - COPY is allowed; files next to this fragment are the build context.
#   - ADD is rejected.
#
# REQUIRED: put a one-line description after the directive below. It is shown
# by ` + "`gbx plugin ls`" + `.
` + descriptionDirective + `
#
# ---- examples (edit or delete) ---------------------------------------
# RUN apt-get update \
#  && apt-get install -y --no-install-recommends htop tree \
#  && rm -rf /var/lib/apt/lists/*
#
# RUN uv tool install httpie
#
# ENV MY_TOOL_HOME=/opt/mytool
# ----------------------------------------------------------------------
`
}
